namespace Maml.UserInput;

internal static class InputHelpers
{

	internal static VirtualKey JSKeyToVirtualKey(string key)
	{
		return key switch
		{
			// Special
			"Unindentified" => VirtualKey.None,
			// Modifier
			"Alt" => VirtualKey.Alt,
			"CapsLock" => VirtualKey.CapitalLock,
			"Control" => VirtualKey.Control,
			"Meta" => VirtualKey.LeftWindows,
			"NumLock" => VirtualKey.NumberKeyLock,
			"ScrollLock" => VirtualKey.Scroll,
			"Shift" => VirtualKey.Shift,
			"SymbolLock" or "Enter" => VirtualKey.Enter,
			"Tab" => VirtualKey.Tab,
			" " => VirtualKey.Space,
			// Navigation
			"ArrowDown" => VirtualKey.Down,
			"ArrowLeft" => VirtualKey.Left,
			"ArrowRight" => VirtualKey.Right,
			"ArrowUp" => VirtualKey.Up,
			"End" => VirtualKey.End,
			"Home" => VirtualKey.Home,
			"PageDown" => VirtualKey.PageDown,
			"PageUp" => VirtualKey.PageUp,
			// Editing
			"Backspace" => VirtualKey.Back,
			"Delete" => VirtualKey.Delete,
			"Insert" => VirtualKey.Insert,
			// UI
			"Accept" => VirtualKey.Accept,
			"Cancel" => VirtualKey.Cancel,
			"ContextMenu" => VirtualKey.Context,
			"Escape" => VirtualKey.Escape,
			"Execute" => VirtualKey.Execute,
			"Help" => VirtualKey.Help,
			"Pause" => VirtualKey.Pause,
			"Select" => VirtualKey.Select,
			// IME
			"NonConvert" => VirtualKey.NonConvert,
			"Convert" => VirtualKey.Convert,
			"FinalMode" => VirtualKey.Final,
			"ModeChange" => VirtualKey.ModeChange,
			// Korean
			"HangulMode" => VirtualKey.Hangul,
			"HanjalMode" => VirtualKey.Hanja,
			"JunjaMode" => VirtualKey.Junja,
			// Japanese
			"KanaMode" => VirtualKey.Kana,
			"KanjiMode" => VirtualKey.Kanji,
			// Function
			"F1" => VirtualKey.F1,
			"F2" => VirtualKey.F2,
			"F3" => VirtualKey.F3,
			"F4" => VirtualKey.F4,
			"F5" => VirtualKey.F5,
			"F6" => VirtualKey.F6,
			"F7" => VirtualKey.F7,
			"F8" => VirtualKey.F8,
			"F9" => VirtualKey.F9,
			"F10" => VirtualKey.F10,
			"F11" => VirtualKey.F11,
			"F12" => VirtualKey.F12,
			"F13" => VirtualKey.F13,
			"F14" => VirtualKey.F14,
			"F15" => VirtualKey.F15,
			"F16" => VirtualKey.F16,
			"F17" => VirtualKey.F17,
			"F18" => VirtualKey.F18,
			"F19" => VirtualKey.F19,
			"F20" => VirtualKey.F20,
			// Document
			"Print" => VirtualKey.Print,
			// Browser control
			"BrowserBack" => VirtualKey.GoBack,
			"BrowserFavorites" => VirtualKey.Favorites,
			"BrowserForward" => VirtualKey.GoForward,
			"BrowserHome" => VirtualKey.GoHome,
			"BrowserRefresh" => VirtualKey.Refresh,
			"BrowserSearch" => VirtualKey.Search,
			"BrowserStop" => VirtualKey.Stop,
			// Numeric keypad
			"Decimal" or "." => VirtualKey.Decimal,
			"Multiply" or "*" => VirtualKey.Multiply,
			"Add" or "+" => VirtualKey.Add,
			"Clear" => VirtualKey.Clear,
			"Divide" or "/" => VirtualKey.Divide,
			"Subtract" or "-" => VirtualKey.Subtract,
			"Separator" => VirtualKey.Separator,
			"0" => VirtualKey.Number0,
			"1" => VirtualKey.Number1,
			"2" => VirtualKey.Number2,
			"3" => VirtualKey.Number3,
			"4" => VirtualKey.Number4,
			"5" => VirtualKey.Number5,
			"6" => VirtualKey.Number6,
			"7" => VirtualKey.Number7,
			"8" => VirtualKey.Number8,
			"9" => VirtualKey.Number9,
			// Letter
			"a" or "A" => VirtualKey.A,
			"b" or "B" => VirtualKey.B,
			"c" or "C" => VirtualKey.C,
			"d" or "D" => VirtualKey.D,
			"e" or "E" => VirtualKey.E,
			"f" or "F" => VirtualKey.F,
			"g" or "G" => VirtualKey.G,
			"h" or "H" => VirtualKey.H,
			"i" or "I" => VirtualKey.I,
			"j" or "J" => VirtualKey.J,
			"k" or "K" => VirtualKey.K,
			"l" or "L" => VirtualKey.L,
			"m" or "M" => VirtualKey.M,
			"n" or "N" => VirtualKey.N,
			"o" or "O" => VirtualKey.O,
			"p" or "P" => VirtualKey.P,
			"q" or "Q" => VirtualKey.Q,
			"r" or "R" => VirtualKey.R,
			"s" or "S" => VirtualKey.S,
			"t" or "T" => VirtualKey.T,
			"u" or "U" => VirtualKey.U,
			"v" or "V" => VirtualKey.V,
			"w" or "W" => VirtualKey.W,
			"x" or "X" => VirtualKey.X,
			"y" or "Y" => VirtualKey.Y,
			"z" or "Z" => VirtualKey.Z,
			_ => VirtualKey.None,
		};
	}
}